name: phpstan

on: ['push']

jobs:

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_extensions: curl, mbstring, zip, pcntl, intl

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@master
        with:
          configuration: phpstan.neon.dist
          php_version: 8.1
          php_extensions: curl, mbstring, zip, pcntl, intl
          memory_limit: 256M
