name: Static Analysis

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'


jobs:

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [lowest, stable]

    name: PHPStan ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, mbstring, zip, pcntl, intl
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-${{ matrix.dependency-version }} --no-interaction --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress --error-format=github
