name: Code Style

on: ['push']

jobs:

  php-cs-fixer:
    runs-on: ubuntu-latest

    name: php-cs-fixer

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, mbstring, zip, pcntl, intl
          coverage: none

      - name: Install Dependencies
        run: composer update --prefer-stable --no-interaction --no-progress

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix -v --allow-risky=yes --dry-run

